background = '#101319'
foreground = '#cdd6f4'

currentline = '#171b24'

text = '#1a2137'
cursor = '#bcc6e3'

[colors.strong]
black = '#2e3859'
red = '#fb80aa'
green = '#83C092'
yellow = '#e5c890'
blue = '#56b8f7'
violet = '#b77ed1'
cyan = '#52a9a9'
white = '#bac2de'

